"""database v1.3

Revision ID: 17aeb88aea3d
Revises: 5537b6052499
Create Date: 2016-04-19 20:50:50.572030

"""

# revision identifiers, used by Alembic.
revision = '17aeb88aea3d'
down_revision = '5537b6052499'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
