"""database v1.3

Revision ID: 5537b6052499
Revises: 4397a3de5953
Create Date: 2016-04-19 20:50:30.465572

"""

# revision identifiers, used by Alembic.
revision = '5537b6052499'
down_revision = '4397a3de5953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
